---
title: "Safety Mode Tests"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Safety Mode Tests}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(mic.sim)
library(mgcv)
library(dplyr)
library(ggplot2)
library(ggnewscale)
library(survival)
```

```{r}
set.seed(1)
n = 300
ncomp = 2
pi = function(t) {
  z <- 0.07 + 0.03 * t - 0.00045 * t^2
  #z <- (1+ exp(-m))^-1 #if exp(m) gets large, it won't add the 1 so we write like this
  tibble("1" = 1 - z, "2" = z)
}
`E[X|T,C]` = function(t, c)
{
  case_when(
    c == "1" ~ -4.3 + (0.34 * t) - (0.0095 * t^2),
    c == "2" ~ 3 + 0.001 * t,
    TRUE ~ NaN
  )
}
t_dist = function(n){runif(n, min = 0, max = 16)}
attr(t_dist, "min") = 0
attr(t_dist, "max") = 16
sd_vector = c("1" = 1, "2" = 1.05)
low_con = -3
high_con = 0
scale = "log"
example_data = simulate_mics(n = n, t_dist = t_dist, pi = pi, `E[X|T,C]` = `E[X|T,C]`, sd_vector = sd_vector, covariate_list = NULL, covariate_effect_vector = c(0), low_con = low_con, high_con = high_con, scale = "log") %>% suppressMessages()

example_data %>% 
  mutate(verbose_comp = case_when(
    comp == 1 ~ "Component 1",
    TRUE ~ "Component 2"
  )) %>% 
  ggplot() +
  geom_segment(aes(x = t, xend = t, y = left_bound, yend = right_bound, color = verbose_comp), data = (. %>% filter(left_bound != -Inf & right_bound != Inf)), alpha = 0.3) +
  geom_segment(aes(x = t, xend = t, y = right_bound, yend = left_bound, color = verbose_comp), data = (. %>% filter(left_bound == -Inf) %>% mutate(left_bound = low_con - 2)), arrow = arrow(length = unit(0.03, "npc")), alpha = 0.3) +
  geom_segment(aes(x = t, xend = t, y = left_bound, yend = right_bound, color = verbose_comp), data = (. %>% filter(right_bound == Inf) %>% mutate(right_bound = 5)), arrow = arrow(length = unit(0.03, "npc")), alpha = 0.3) +
  geom_point(aes(x = t, y = left_bound, color = verbose_comp), data = . %>% filter(left_bound != -Inf), alpha = 0.3) +
  geom_point(aes(x = t, y = right_bound, color = verbose_comp), data = . %>% filter(right_bound != Inf), alpha = 0.3) +
  geom_function(fun = function(t){`E[X|T,C]`(t, c = "1")}, aes(color = "Component 1 Mean")) +
  geom_function(fun = function(t){`E[X|T,C]`(t, c = "2")}, aes(color = "Component 2 Mean")) +
  xlim(attr(t_dist, "min") ,attr(t_dist, "max")) +
  ylim(low_con - 2, 5)
```

```{r}
output_mgcv = example_data %>% 
  EM_algorithm_safety_mgcv(., 
                           mu_formula = yi ~ s(t), 
                           pi_formula = c == "2" ~ s(t),
                           censored_side = "RC",
                           max_it = 3000,
                           ncomp = 2,
                           tol_ll = 1e-06,
                           browse_at_end = FALSE,
                           browse_each_step = FALSE,
                           plot_visuals = FALSE,
                           prior_step_plot = FALSE,
                           pause_on_likelihood_drop = FALSE,
                           pi_link = "logit",
                           verbose = 3,
                           model_coefficient_tolerance = 1e-05,
                           extra_row = FALSE
                           )
plot_likelihood(output_mgcv$likelihood, format = "tibble")
```
```{r}
plot_fms(output_mgcv, title = "mgcv", cens_dir = "RC", mode = "mgcv", add_log_reg = FALSE, s_breakpoint = NULL, r_breakpoint = NULL)
```



```{r}
output_surv = example_data %>% 
  EM_algorithm_safety_surv(., 
                           mu_formula = Surv(time = left_bound, time2 = right_bound, type = "interval2") ~ pspline(t, df = 0, caic = TRUE), 
                           pi_formula = c == "2" ~ s(t),
                           censored_side = "RC",
                           max_it = 3000,
                           ncomp = 2,
                           tol_ll = 1e-06,
                           browse_at_end = FALSE,
                           browse_each_step = FALSE,
                           plot_visuals = FALSE,
                           prior_step_plot = FALSE,
                           pause_on_likelihood_drop = FALSE,
                           pi_link = "logit",
                           verbose = 3,
                           model_coefficient_tolerance = 1e-05,
                           extra_row = FALSE,
                           stop_on_likelihood_drop = FALSE
                           )
plot_likelihood(output_surv$likelihood, format = "tibble")
```
```{r}
plot_fms(output_surv, title = "surv", cens_dir = "RC", mode = "surv", add_log_reg = FALSE, s_breakpoint = NULL, r_breakpoint = NULL)
```

